### ISSUE TITLE
Use as a library?

### ISSUE THREAD

**Issue by kylecordes** [Cellarise/oauth-rest-atlassian#3]
I was able to successfully connect to a JIRA instance using this module, following the directions. This is quite heartening, as OAuth is notoriously tricky and there are a variety of solutions and obsolete instructions online, countless ways you can fail to connect to JIRA using OAuth.

However, it is unclear how to go past just a brief demo. This node module appears to be packaged in a very unusual way, in which the intended usage is to edit the configuration inside the module; I don't see any clear way to use this as a library, as noted modules are almost always used.

Is this module intended to be usable as a library, to enable OAuth authentication to Atlassian products? Or only as a standalone demo?

**Comment by JohnMBarry** [comment]
Currently the package does have a dual personality with the authorisation dance designed to be performed from within the module, but the REST API usable as a library.

Once you have the access tokens after successfully completing the authorisation dance you can take the config and pass it directly to the rest function of the module. 

```
var opts;
opts.config = require('<path to config file>').jira
opts.query = 'project'; //get all Jira projects
require('oauth-rest-atlassian').rest(opts, function(err, data){
//data contains the list of Jira projects
});
```

I use a standalone install of the module to perform the authorisation dance.

I use the module as a traditional package in my development projects where the config sits in the project or as part of the environment.

**Comment by kylecordes** [comment]
Thank you, that is very helpful!
